bioreactor/views/frontend.py
from sqlalchemy import desc
from flask import Blueprint, current_app, session, request, render_template, \
                  redirect

from bioreactor.models import Job

# because current_app.config is not available outside the application context
frontend = Blueprint('frontend', __name__)


@frontend.route('/')
def home():
    joblist = []
    firstlaunch_cookie = 0
    if 'bioreactor_firstlaunch' in request.cookies:
        firstlaunch_cookie = request.cookies['bioreactor_firstlaunch']
    try:
        joblist = Job.query.order_by(desc(Job.created_at)).limit(5).all()
    finally:
        return render_template('home.html', job_list=joblist, narrow=True,
                               firstlaunch_cookie=firstlaunch_cookie)


@frontend.route('/about')
def about():
    return render_template('about.html')


@frontend.route('/search')
def search_results():
    return render_template('search_results.html')

bioreactor/views/jobs.py
import os
from sqlalchemy import desc
from flask import Blueprint, session, request, flash, render_template, \
                  redirect, url_for, abort

from bioreactor.extensions import db
from bioreactor.models import Organism, Job

jobs = Blueprint('jobs', __name__)


@jobs.route('/jobs/')
def job_list():
    joblist = []
    try:
        joblist = Job.query.order_by(desc(Job.created_at)).all()
    finally:
        return render_template('jobs.html', job_list=joblist)


@jobs.route('/jobs/<id>')
def results_for_job_id(id):
    # FIXME: This doesn't actually return any "results," just the same
    # information about the job that you see in the job list
    job_result=[]
    try:
        job_result = Job.query.filter(Job.id == id).first()
    finally:
        return render_template('job_result.html', job_result=job_result)


@jobs.route('/jobs/add', methods=['GET'])
def add_job():
    return render_template('add_job.html')

@jobs.route('/jobs/add', methods=['POST'])
def add_job_post():
    if not session.get('logged_in'):
        abort(401)

    job = Job(name=request.form['name'],
              description=request.form['description'],
              notification_email=request.form['email'])
    db.session.add(job)
    db.session.commit()
    flash('New job was successfully submitted')
    return redirect(url_for('jobs.job_list'))

bioreactor/templates/partials/footer.html
<!-- partials/footer.html -->
    <nav class="navbar navbar-default navbar-fixed-bottom">
      <div class="container">
        <div class="col-md-12 navbar-text text-muted text-center">
          a <a href="https://github.com/WeirauchLab">Weirauch Lab</a>
          production | <a href="{{ url_for('frontend.about') }}">about</a>
        </div>
      </div> <!-- /.container -->
    </nav>

bioreactor/templates/partials/input_form.html
{#-
    Input form for new analysis jobs
-#}
          <!-- input_form.html >>> -->
          <form class="form-horizontal" action="{{ url_for('jobs.add_job_post') }}"
           method="post" class="add-entry">
            <div class="form-group">
              <label for="name" class="col-sm-3 control-label">Job name:</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" id="name"
                 name="name">
              </div>
            </div>

            <div class="form-group">
              <label for="description" class="col-sm-3 control-label">Job
                description:</label>
              <div class="col-sm-9">
                <input type="text" class="form-control" id="description"
                 name="description">
              </div>
            </div>

            <div class="form-group">
              <label for="email" class="col-sm-3 control-label">Contact Email:</label>
              <div class="col-sm-9">
                <input type="email" class="form-control" id="email"
                 name="email">
              </div>
            </div>

            <div class="form-group text-right">
              <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" value="submit"
                 class="btn btn-lg btn-primary">Submit</button>
              </div>
            </div>
          </form>
          <!-- <<< input_form.html -->

bioreactor/templates/partials/job_list.html
{#-
    List of previously-run jobs
-#}
          <!-- job_list.html >>> -->
          <ul class="entries">
          {%- for job in job_list %}
            <li>
              <h3>
                <a title="View complete job results"
                 href="{{ url_for('jobs.results_for_job_id', id=job.id) }}">
                  #{{ job.id }}: {{ job.name }}</a>
              </h3>
              {{ job.description }}
              {% if narrow %}<br>{% else %}&mdash; submitted by {% endif %}
              &lt;{{ job.notification_email }}&gt;
              <abbr title="{{ job.created_at }}"><em>{{ job.created_at|humantime }}</em></abbr>
            </li>
          {%- else %}
            <li><em>No jobs in the job history</em></li>
          {%- endfor %}
          </ul>
          <!-- <<< job_list.html -->

bioreactor/templates/partials/job_results.html
{% extends "base.html" %}
{% block content %}
  <div class="row">
    <ol class="breadcrumb">
      <li><a href="{{ url_for('frontend.home') }}">Home</a></li>
      <li class="active">{{ job_result.id }}</li>
    </ol>
  </div>

  {%- if session.logged_in %}
  <a title="Add a new job" class="btn btn-primary" href="{{ url_for('frontend.home') }}">
    Add a new job
  </a>
  {%- endif %}
  <h2>#{{ job_result.id }}: {{ job_result.description }} </h2>
  {{ job_result.username|safe }} &lt;{{ job_result.notification_email }}&gt;<br>
  {{ job_result.description|safe }}
  &mdash;<abbr title="{{ job_result.creation }}"><em>{{ job_result.creation }}</em></abbr>
{% endblock %}

bioreactor/templates/partials/search_form.html
{#-
    Search form for existing organisms (results)
-#}
          <!-- search_form.html >>> -->
          <form id="search-form" action="/search_results" method="post">
            <div class="form-group">
              <div class="input-group select2-bootstrap-append">
                <select name="search-input" id="search-input"
                 class="form-control" multiple="multiple" tabindex="-1"
                 autofocus="autofocus" aria-label="...">
                </select>

                <span class="input-group-btn">
                  <button id="search-submit" type="submit"
                   class="btn btn-primary">
                     <span class="glyphicon glyphicon-search"></span>
                  </button>
                </span>
                                                                        
                <!--div class="input-group-btn">
                  <button type="button" class="btn btn-default">Action</button>
                  <button type="button" class="btn btn-default dropdown-toggle"
                   data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">
                    <span class="caret"></span>
                    <span class="sr-only">Toggle Dropdown</span>
                  </button>
                  <ul class="dropdown-menu">
                    <li><a href="#">Run with defaults (default)</a></li>
                    <li><a href="#">Modify parameters</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Other options...</a></li>
                  </ul>
                </div--> <!-- /.input-group-btn -->
              </div> <!-- /.input-group -->
            </div> <!-- /.form-group -->

            <div class="form-group">
              <textarea id="search-results" placeholder="Search results"
               class="form-control" rows="5" disabled="disabled"
               style="font-family:monospace"></textarea>
            </div>
            <div class="form-group text-right">
              <button id="search-reset" class="btn btn-lg btn-default"
               type="reset">Reset</button>
            </div>
          </form>
          <!-- <<< search_form.html -->

bioreactor/templates/partials/tree.html
  <div class="steps">
    <div class="step step4">
      <p class="branchlbl clave">Homo</p>
      <p id="br4" class="branchlbl qty collapser">25</p>
    </div>
    <div class="step step3">
      <p class="branchlbl clave">Animalia</p>
      <p id="br3" class="branchlbl qty collapser">50</p>
    </div>
    <div class="step step2">
      <p class="branchlbl clave">Archaea</p>
      <p id="br2" class="branchlbl qty collapser">75</p>
    </div>
    <div class="step baseline">
      <p id="br1" class="branchlbl qty">150</p>
    </div>
  </div>