bioreactor/models/job.py
"""
Job Model for Bioreactor
"""
from datetime import datetime as dt
from uuid import uuid4

from bioreactor.extensions import db
from .user import User

def id_generator(size=10):
    """
    Return a hex job ID (default 10 digits)

    >>> id_generator(9)
    Traceback (most recent call last):
    ...
    ValueError: size must be between 10 and 40
    >>> id_generator(41)
    Traceback (most recent call last):
    ...
    ValueError: size must be between 10 and 40
    >>> len(id_generator(14)) == 14
    True
    """
    if size < 10 or size > 40:
        raise ValueError('size must be between 10 and 40')

    return uuid4().get_hex()[0:size]


def populate_jobs():
    """
    Fill the 'jobs' table with a bunch of random jobs
    """
    for x in range(1,11):
        db.session.add(Job(name='Test job #%s' % x, user_id=x,
                           description='A longer description of the test job',
                           notification_email='nobody@example.org'))
    db.session.commit()


class Job(db.Model):
    """A cluster job and some details about it"""
    id = db.Column(db.Integer, primary_key=True)
    jobid = db.Column(db.String(40), unique=False, nullable=False)
    uuid = db.Column(db.String(40), unique=True, nullable=False)
    name = db.Column(db.String(80))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    submitted_by = db.relationship('User', backref=db.backref('jobs',
            lazy='dynamic'))
    notification_email = db.Column(db.String(256))
    description = db.Column(db.Text)
    created_at = db.Column(db.DateTime(timezone=True), nullable=False)
    parameters = db.Column(db.Text)

    def __init__(self, name=None, user_id=None, description=None,
                notification_email=None):
        self.jobid = id_generator()
        self.uuid = uuid4().get_hex()
        self.name = name
        self.user_id = user_id
        self.description = description
        self.notification_email = notification_email
        self.created_at = dt.now()
        self.parameters = '{}'

    def __repr__(self):
        return '<Job: %s, %s>' % (self.jobid, self.name)

    def __str__(self):
        return self.name

bioreactor/views/account.py
import os
from flask import Blueprint, current_app, session, request, flash, \
                  render_template, redirect, url_for

from bioreactor.extensions import db
from bioreactor.models import User

account = Blueprint('account', __name__)


@account.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        if request.form['username'] != current_app.config['USERNAME']:
            error = 'Invalid username'
        elif request.form['password'] != current_app.config['PASSWORD']:
            error = 'Invalid password'
        else:
            session['logged_in'] = True
            flash('You were logged in')
            return redirect(url_for('frontend.home'))

    return render_template(
        'login.html', error=error,
        default_username=current_app.config['USERNAME'],
        default_password=current_app.config['PASSWORD']
    )


@account.route('/logout')
def logout():
    session.pop('logged_in', None)
    flash('You were logged out')
    return redirect(url_for('frontend.home'))

bioreactor/views/contact.py
from flask import Blueprint, flash, request, redirect, render_template, \
                  current_app, url_for, make_response, g

contact = Blueprint('contact', __name__)

@contact.before_request
def check_celery():
    from bioreactor.tasks import BioreactorTaskQueueUnavailable, \
                                 get_celery_worker_status
    try:
        g.celery_unavailable = False;  # this is sketchy
        get_celery_worker_status()
    except BioreactorTaskQueueUnavailable:
        g.celery_unavailable = True;
        # FIXME: The Boostrap style isn't getting picked up here.
        flash('Background task processor unavailable!', category='error')


@contact.route('/')
def form():
    return render_template('contact.html')


@contact.route('/post', methods=['POST'])
def post():
    from bioreactor.extensions import mail
    from bioreactor.tasks import add, send_mail

    # FIXME: use validate_email to check this out. Also, what if they're blank?
    sender = '"{}" <{}>'.format(request.form['name'],
                                request.form['email'])
    subject = current_app.config['APP_NAME'] + ' contact form'
    recipient = current_app.config['ADMIN_EMAIL']
    body = request.form['message']

    if g.celery_unavailable:
        send_mail(subject=subject, recipient=recipient, reply_to=sender,
                  body=body)
        flash('Your message was sent. Thanks!')
    else:
        send_mail.delay(subject=subject, recipient=recipient, reply_to=sender,
                        body=body)
        flash('Your message was sent (deferred). Thanks!')

    return redirect(url_for('.form'))

bioreactor/views/jobs.py
import os
from sqlalchemy import desc
from flask import Blueprint, session, request, flash, render_template, \
                  redirect, url_for, abort

from bioreactor.extensions import db
from bioreactor.models import Organism, Job

jobs = Blueprint('jobs', __name__)


@jobs.route('/jobs/')
def job_list():
    joblist = []
    try:
        joblist = Job.query.order_by(desc(Job.created_at)).all()
    finally:
        return render_template('jobs.html', job_list=joblist)


@jobs.route('/jobs/<id>')
def results_for_job_id(id):
    # FIXME: This doesn't actually return any "results," just the same
    # information about the job that you see in the job list
    job_result=[]
    try:
        job_result = Job.query.filter(Job.id == id).first()
    finally:
        return render_template('job_result.html', job_result=job_result)


@jobs.route('/jobs/add', methods=['GET'])
def add_job():
    return render_template('add_job.html')

@jobs.route('/jobs/add', methods=['POST'])
def add_job_post():
    if not session.get('logged_in'):
        abort(401)

    job = Job(name=request.form['name'],
              description=request.form['description'],
              notification_email=request.form['email'])
    db.session.add(job)
    db.session.commit()
    flash('New job was successfully submitted')
    return redirect(url_for('jobs.job_list'))

bioreactor/templates/about.html
{% extends "base.html" %}
{% block content %}
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>About Bioreactor</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Available Data Sets</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Getting Help</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>
{% endblock %}

bioreactor/templates/add_job.html
{% extends "base.html" %}
{% block content %}
  <div class="row">
    <ol class="breadcrumb">
      <li><a href="{{ url_for('frontend.home') }}">Home</a></li>
      <li><a title="All completed jobs" href="{{ url_for('jobs.job_list') }}">Jobs</a></li>
      <li class="active">Add a new job</li>
    </ol>
  </div>

  <div class="row">
    <div class="col-md-6">
      <h2>Submit a new job</h2>
      {%- if session.logged_in %}
      {% include "partials/input_form.html" %}
      {%- else -%}
      <div class="alert alert-info">
        You need to <a href="{{ url_for('account.login') }}">log in</a> to submit jobs.
      </div>
      {%- endif %}
    </div><!--/.col-md-6-->
  </div><!--/.row-->
{% endblock %}

bioreactor/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/utils.html" as utils %}
{% from "macros.html" import nav_link, img_url, stylesheet, img with context %}
{% block title %}{{ config.APP_NAME }}{% endblock %}
{%- block head %}
    {{ super() }}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {{ stylesheet('bootstrap.min.css') }}
    {{ stylesheet('style.css') }}
    <link rel="shortcut icon" href="{{ img_url('chemical.png') }}">
{%- endblock %}

{%- block body %}
{#- See: https://pythonhosted.org/Flask-Bootstrap/faq.html#why-is-bootstrap-javascript-not-loading #}
    {%- block navbar %}
    <!-- navbar -->
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{{ url_for('frontend.home') }}">
            {{ img('chemical.png') }}
          </a>
          <a class="navbar-brand" title="Go to the start page"
            href="{{ url_for('frontend.home') }}">{{ config.APP_NAME }}</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          {#- nav_link('worklog', 'work log') -#}
          <li><a href="{{ url_for('contact.form') }}">contact</a></li>
          <li>
            {%- if not session.logged_in %}
              <a href="{{ url_for('account.login') }}">log in</a>
            {%- else %}
              <a href="{{ url_for('account.logout') }}">log out</a>
            {%- endif %}
          </li>
        </ul>
      </div> <!-- /.container -->
    </nav> <!-- /.navbar -->
    {%- endblock %}

    {%- with messages = get_flashed_messages(with_categories=True) %}
    {%- if messages %}
      <div class="row">
        <div class="col-md-12">
          {{ utils.flashed_messages(messages, dismissible=True) }}
        </div>
      </div>
    {%- endif %}
    {%- endwith %}

    <!-- content -->
    <div class="container">
      {%- block content %}{% endblock %}
    </div>
    <!-- /content -->

    {% include 'partials/footer.html' %}

    <!-- scripts -->
{%- block scripts %}
    {{- super() }}
{%- endblock %}
    <!-- /scripts -->
{%- endblock %}

bioreactor/templates/contact.html
{% extends "base.html" %}
{% block content %}
{# source: https://github.com/jonmbake/bootstrap3-contact-form #}
{# license: MIT #}
    <div class="container">
      <div id="contact_form" class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <h2>Contact Us</h2>
          <form role="form" id="feedbackForm"  data-toggle="validator"
                data-disable="false" method="post" action="{{ url_for('.post') }}">
            <div class="form-group">
              <label class="control-label" for="name">Name *</label>
              <!--<div class="input-group">-->
                <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name" required/>
                <!--<span class="input-group-addon"><i class="glyphicon glyphicon-unchecked form-control-feedback"></i></span>-->
              <!--</div>-->
              <span class="help-block" style="display: none;">Please enter your name.</span>
            </div>
{# UNCOMMENT HERE IF YOU WANT TITLE, COMPANY, WEBSITE OR PHONE FIELDS
            <div class="form-group">
              <label class="control-label" for="title">Title</label>
              <input type="text" class="form-control optional" id="title" name="title" />
            </div>
            <div class="form-group">
              <label class="control-label" for="company">Company</label>
              <input type="text" class="form-control optional" id="company" name="company" />
            </div>
            <div class="form-group">
              <label class="control-label" for="website">Website</label>
              <input type="url" class="form-control optional" id="website" name="website" />
            </div>
            <div class="form-group">
              <label class="control-label" for="phone">Phone</label>
              <input type="tel" class="form-control optional" id="phone" name="phone" placeholder="Enter your phone (Optional)"/>
              <span class="help-block" style="display: none;">Please enter a valid phone number.</span>
            </div>
#}
            <div class="form-group">
{#
              <label class="control-label" for="email">Reason for Contact *</label>
              <select name="reason" class="form-control" required>
                <option value="General Inquiry">General Inquiry</option>
                <option value="Place Order">Place Order</option>
                <option value="Report Issue">Report Issue</option>
              </select>
#}
              <span class="help-block" style="display: none;">Please enter a valid e-mail address.</span>
            </div>
            <div class="form-group">
              <label class="control-label" for="email">Email Address *</label>
              <!--<div class="input-group">-->
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email" required/>
                <!--<span class="input-group-addon"><i class="glyphicon glyphicon-unchecked form-control-feedback"></i></span>-->
              <!--</div>-->
              <span class="help-block" style="display: none;">Please enter a valid e-mail address.</span>
            </div>
            <div class="form-group">
              <label class="control-label" for="message">Message *</label>
              <!--<div class="input-group">-->
                <textarea rows="5" cols="30" class="form-control" id="message" name="message" placeholder="Enter your message" required></textarea>
                <!--<span class="input-group-addon"><i class="glyphicon glyphicon-unchecked form-control-feedback"></i></span>-->
              <!--</div>-->
              <span class="help-block" style="display: none;">Please enter a message.</span>
            </div>
{#
            <div class="form-group">
              <div class="g-recaptcha" data-sitekey="your_site_key"></div>
              <span class="help-block" style="display: none;">Please check that you are not a robot.</span>
            </div>
            <span class="help-block" style="display: none;">Please enter a the security code.</span>
#}
            <button type="submit" id="feedbackSubmit" class="btn btn-primary btn-lg"
                    data-loading-text="Sending..." {% if g.celery_unavailable -%}
                    disabled="disabled" title="Unable to send email! Check server logs."
                    {%- endif %}>
              Send Feedback
            </button>
          </form>
        </div><!--.col-md-8-->
        <div class="col-md-2"></div>
      </div><!--/row-->
    </div><!--/.container-->
{% endblock %}

bioreactor/templates/home.html
{% extends "base.html" %}
{% from "macros.html" import stylesheet, javascript %}
{% block head %}
    {{ super() }}  
    {{ stylesheet('select2.min.css') }}
    {{ stylesheet('select2-bootstrap.min.css') }}
{% endblock %}
{% block content %}
      <div class="row">
        <ol class="breadcrumb">
          <li class="active">Home</li>
          <li><a title="All completed jobs" href="{{ url_for('jobs.job_list') }}">Jobs</a></li>
          <li><a title="Add a new job" href="{{ url_for('jobs.add_job') }}">Add a new job</a></li>
        </ol>
      </div><!--/.row-->

      <div class="row">
        <div class="col-md-6">
          <h2>Select a dataset</h2>
          <form id="datasets-select">
            <select id="datasets" multiple class="form-control" size="5">
            </select>
          </form>

          <h2>Search for existing organisms</h2>
          {% include "partials/search_form.html" %}
          {%- if session.logged_in %}
          <h2>Start a new analysis</h2>
          {% include "partials/input_form.html" %}
          {%- endif %}
        </div><!--/.col-md-6-->

        <!-- just a bit of spacing -->
        <div class="col-md-1"></div>

        <div class="col-md-5">
          <h2>Previously completed jobs</h2>
          [<a title="See all completed jobs" href="{{ url_for('jobs.job_list') }}">see all</a>]

          {% include "partials/job_list.html" %}
        </div>
      </div> <!--/.row-->
{% endblock %}
{% block scripts %}
    {{ super() }}
    {{ javascript('select2.js') }}

    {#- set this here in global scope so the 'url_root' will get substituted #}
    <script>$API_ROOT = '{{ request.url_root }}';</script>
    {{ javascript('organism_search.js') }}

    <!-- Example of building a multi-select control from a JSON data source -->
    <script>
      'use strict';
      // === jQuery method ===
      //$.ajax('static/datasets.json').done(function(data) {
      //  data.forEach(function(e) {
      //    $('#datasets')
      //      .append('<option value="' + e.name + '">' + e.name + '</option>');
      //  });
      //})

      // === VanillaJS method ===
      var $DATASETS = '/static/datasets.json';

      function getXHR() {
        var xhr = null;
        if (window.XMLHttpRequest) {
          xhr = new XMLHttpRequest();
        } else if (window.ActiveXObject) { // for IE
          xhr = new ActiveXObject('MSXML2.XMLHTTP.3.0');
        }
        return xhr;
      }

      var xhr = getXHR();
      if (!xhr) {
        throw new Error("Oh, bother. Couldn't get an XMLHttpRequest object.");
      }

      xhr.open('GET', $DATASETS, true); // "true" means async
      xhr.send(null);
      xhr.onreadystatechange = function() {
        if (xhr.readyState === XMLHttpRequest.DONE) {
          if (xhr.status !== 200) {
            throw new Error("Oh, bother. Async request failed.");
          }

          // sort the response (case-insensitively) by dataset name
          var response = JSON.parse(xhr.responseText);
          response.sort(function(a, b) {
              if (a.name.toUpperCase() < b.name.toUpperCase()) {
                return -1;
              } else if (a.name.toUpperCase() > b.name.toUpperCase()) {
                return 1;
              } else return 0;
          });

          var datasets = document.getElementById('datasets');
          response.forEach(function(e) {
            // var opt = new Option(e.name, e.id); // non-standard?
            // the old-fashioned way (better: 'new Option(e.id, e.name)'?)
            var opt = document.createElement('option');
            opt.setAttribute('value', e.id);
            opt.textContent = e.name;
            datasets.appendChild(opt);
          }); // for each array element in JSON response
        } // if XHR readyState === DONE
      }; // onreadystatechange handler
    </script>
{% endblock %}

bioreactor/templates/login.html
{% extends "base.html" %}
<!-- login.html -->
{% block content %}
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <h2>Login</h2>
      {% if error %}<p class="error"><strong>Error:</strong> {{ error }}{% endif %}

      <form action="{{ url_for('account.login') }}" method="post">
        <div class="form-group">
          <label for="username">
          {%- if is_dev_server() %}
            Username {% if default_username %}({{ default_username }}){% endif %}:
          {%- else %}
            Username:
          {%- endif %}
          </label>
          <input type="text" class="form-control" id="username" name="username"
           placeholder="Username">
        </div> <!-- /.form-group -->

        <div class="form-group">
          <label for="username">
          {%- if is_dev_server() %}
            Password {% if default_password %}({{ default_password }}){% endif %}:
          {%- else %}
            Password:
          {%- endif %}
          </label>
          <input type="password" class="form-control" name="password"
           placeholder="Password">
        </div> <!-- /.form-group -->

        <div class="form-group">
          <input class="btn btn-primary" type="submit" value="Login">
        </div> <!-- /.form-group -->
      </form>
    </div> <!-- /.col-md-8 -->

    <div class="col-md-4"></div>
  </div> <!-- /.row -->
{% endblock %}

bioreactor/templates/search_results.html
{% extends "base.html" %}
{% block content %}
  <div class="row">
    <ol class="breadcrumb">
      <li><a href="{{ url_for('frontend.home') }}">Home</a></li>
      <li><a href="{{ url_for('search_results') }}">Search</a></li>
      <li class="active">what ever</li>
    </ol>
  </div>
{% endblock %}

bioreactor/templates/virint_home.html
{% extends "base.html" %}
{% from "macros.html" import stylesheet, javascript %}
{% block head %}
    {{ super() }}
    {{ stylesheet('select2.min.css') }}
    {{ stylesheet('select2-bootstrap.min.css') }}
{% endblock %}
{% block content %}
    <div class="row">
        <ol class="breadcrumb">
            <li class="active">Home</li>
            <li><a title="All completed jobs" href="{{ url_for('jobs.job_list') }}">Jobs</a></li>
            <li><a title="Add a new job" href="{{ url_for('jobs.add_job') }}">Add a new job</a></li>
        </ol>
    </div><!--/.row-->

    <div>
        {%- if firstlaunch_cookie == 0 %}
            {% include 'partials/home/about_help.html' %}
        {%- endif %}
    </div>


    <form id="inputform" name="inputform" method="post" accept-charset="UTF-8"
          enctype="multipart/form-data">
        {% include 'partials/home/new_job' %}

        <br/>
        <br/>


        <div id="phenotypes" style="padding-right: 50px; padding-left: 50px">
            <div>
                <input class="col-md-5" placeholder="Select Phenotype(s)" type="text"/>
                <div class="col-md-1" style="width:0"></div>
                <input class="col-md-6" placeholder="Input coords/gene/SNPs" type="text"/>
            </div>
            <br/>
            <br/>
            <div>
                <div id="phenotypes_select_box" class="col-md-2">
                    {% include 'partials/home/phenotypes_select_box.html' %}
                </div>
                <div class="col-md-2"></div>
                <div id="search_for_gene" class="col-md-8">
                    {% include 'partials/home/phenotypes_search_for_gene.html' %}
                    {% include 'partials/home/phenotypes_upload_bed.html' %}
                </div>
            </div>
        </div>

        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>

        <div id="parameters_div" style="padding-top:20px">
            <h2 id="new_job_label" style="font-size:30px; font-weight:700; padding-left:15px">
                Parameters:
            </h2>
            <hr/>

            {% include 'partials/home/parameters_specific_viruses.html' %}

            {% include 'partials/home/parameters_upstream.html' %}

            {% include 'partials/home/parameters_data_sets.html' %}
        </div>

        <div id="email_and_job_description" style="padding-top: 150px">
            <div class="col-md-8">
                <div>
                    <label>
                        Notification email:
                        <input type="email">
                    </label>
                </div>
                <div>
                    <label>
                        Job description:
                        <textarea name="textarea" style="width:172px;height:26px;"></textarea>
                    </label>
                </div>
            </div>
            <div class="col-md-4">
                <div>
                    <label>
                        <input type="checkbox" value="create_account">
                        Create account <br/>
                        <p style="font-size:10px; padding-left: 10px">(Supply password in next step)</p>
                    </label>
                </div>
                <div>
                    <label>
                        <input type="checkbox" value="save_inputs">
                        Save these inputs
                    </label>
                </div>
            </div>
        </div>

        <div style="padding-top: 100px">
            <div class="col-md-8"></div>
            <div class="col-md-4">
                <input type="button" value="Reset Form" onclick="this.form.reset()"/>
                <button onclick="submitForm()">Submit</button>
            </div>
        </div>
    </form>

{% endblock %}
{% block scripts %}
    {{ super() }}
    {{ javascript('select2.js') }}

    {#- set this here in global scope so the 'url_root' will get substituted #}
    <script>$API_ROOT = '{{ request.url_root }}';</script>
    {{ javascript('organism_search.js') }}

    <!-- Example of building a multi-select control from a JSON data source -->
    <script>
        'use strict';
        // === jQuery method ===
        //$.ajax('static/datasets.json').done(function(data) {
        //  data.forEach(function(e) {
        //    $('#datasets')
        //      .append('<option value="' + e.name + '">' + e.name + '</option>');
        //  });
        //})

        // === VanillaJS method ===
        var $DATASETS = '/static/datasets.json';

        function getXHR() {
            var xhr = null;
            if (window.XMLHttpRequest) {
                xhr = new XMLHttpRequest();
            } else if (window.ActiveXObject) { // for IE
                xhr = new ActiveXObject('MSXML2.XMLHTTP.3.0');
            }
            return xhr;
        }

        var xhr = getXHR();
        if (!xhr) {
            throw new Error("Oh, bother. Couldn't get an XMLHttpRequest object.");
        }

        xhr.open('GET', $DATASETS, true); // "true" means async
        xhr.send(null);
        xhr.onreadystatechange = function () {
            if (xhr.readyState === XMLHttpRequest.DONE) {
                if (xhr.status !== 200) {
                    throw new Error("Oh, bother. Async request failed.");
                }

                // sort the response (case-insensitively) by dataset name
                var response = JSON.parse(xhr.responseText);
                response.sort(function (a, b) {
                    if (a.name.toUpperCase() < b.name.toUpperCase()) {
                        return -1;
                    } else if (a.name.toUpperCase() > b.name.toUpperCase()) {
                        return 1;
                    } else return 0;
                });

                var datasets = document.getElementById('datasets');
                response.forEach(function (e) {
                    // var opt = new Option(e.name, e.id); // non-standard?
                    // the old-fashioned way (better: 'new Option(e.id, e.name)'?)
                    var opt = document.createElement('option');
                    opt.setAttribute('value', e.id);
                    opt.textContent = e.name;
                    datasets.appendChild(opt);
                }); // for each array element in JSON response
            } // if XHR readyState === DONE
        }; // onreadystatechange handler

        jQuery.fn.filterByText = function (textbox, selectSingleMatch) {
            return this.each(function () {
                var select = this;
                var options = [];
                $(select).find('option').each(function () {
                    options.push({ value: $(this).val(), text: $(this).text() });
                });
                $(select).data('options', options);
                $(textbox).bind('change keyup', function () {
                    var options = $(select).empty().scrollTop(0).data('options');
                    var search = $.trim($(this).val());
                    var regex = new RegExp(search, 'gi');

                    $.each(options, function (i) {
                        var option = options[i];
                        if (option.text.match(regex) !== null) {
                            $(select).append(
                                    $('<option>').text(option.text).val(option.value)
                            );
                        }
                    });
                    if (selectSingleMatch === true &&
                            $(select).children().length === 1) {
                        $(select).children().get(0).selected = true;
                    }
                });
            });
        };

        $('.about-help .panel-body .btn').on('click', function (e) {
            e.preventDefault();
            $('.about-help .panel-body .collapse').collapse('toggle');
        });

        $('#about_got_it_button').on('click', function (e) {
            e.preventDefault();
            document.cookie = "bioreactor_firstlaunch=1;path=/";
            $('.about-help.collapse').collapse('toggle');
        });

        function flipCollapseButton(button) {
            if (button.hasClass('glyphicon-plus')) {
                button.removeClass('glyphicon-plus').addClass('glyphicon-minus');
            } else {
                button.removeClass('glyphicon-minus').addClass('glyphicon-plus');
            }
        }

        $('#parameters_upstream_collapse').on('click', function (e) {
            e.preventDefault();
            $('#parameters_upstream_div .collapse').collapse('toggle');
            var upstream_button = $('#parameters_upstream_div .upstream');
            flipCollapseButton(upstream_button);
        });

        $('#parameters_data_sets_collapse').on('click', function (e) {
            e.preventDefault();
            $('#parameters_data_sets_div .collapse').collapse('toggle');
            var data_sets_button = $('#parameters_data_sets_div .data_sets');
            flipCollapseButton(data_sets_button);
        });

        $('#parameters_specific_viruses_collapse').on('click', function (e) {
            e.preventDefault();
            $('#parameters_specific_viruses_div .collapse').collapse('toggle');
            var specific_viruses_button = $('#parameters_specific_viruses_div .specific_viruses');
            flipCollapseButton(specific_viruses_button);
        });

        $('#select-all-phenotypes').click(function () {
            $('#select_phenotypes option').attr('selected', true);
        });

        $('#deselect-all-phenotypes').click(function () {
            $('#select_phenotypes option').attr('selected', false);
        });

        $('#select-all-available-tracks').click(function () {
            $('#available-tracks option').attr('selected', true);
        });

        $('#deselect-all-available-tracks').click(function () {
            $('#available-tracks option').attr('selected', false);
        });

        $('#select-all-selected-tracks').click(function () {
            $('#selected-tracks option').attr('selected', true);
        });

        $('#deselect-all-selected-tracks').click(function () {
            $('#selected-tracks option').attr('selected', false);
        });

        $(function () {
            $('#select_specific_virus').filterByText($('#textbox_specific_virus'), true);
            $('#select_gene_name').filterByText($('#textbox_gene_name'), true);
        });

        var submitForm = function () {
            console.log('submit form');
        }
    </script>
{% endblock %}